#!/bin/bash

platform=`uname -s`

if [ $platform == 'Darwin' ]; then
    echo "Platform: macOS"
    cp ./ml ./ml.macosx
    sudo rm -f /usr/local/bin/ml
    sudo ln -s `pwd`/ml.macosx /usr/local/bin/ml
else
    echo "Platform: Linux"
    cp ./ml ./ml.linux.64
    sudo rm -f /usr/bin/ml
    sudo ln -s `pwd`/ml.linux.64 /usr/bin/ml
fi

# create the "ml list" shortcut
sudo rm -f /usr/local/bin/mll
sudo ln -s `pwd`/mll /usr/local/bin/mll

